

  Connection
    #find()
      âœ“ respond with matching records

  Connection (save error)
    #find()
      1) "before each" hook for "respond with matching records"


  1 passing (8ms)
  1 failing

  1) Connection (save error)
       #find()
         "before each" hook for "respond with matching records":
     Error: Save error
      at Suite.<anonymous> (test/fixtures/asynchronous-hooks.test.js:56:18)
      at Object.<anonymous> (test/fixtures/asynchronous-hooks.test.js:50:1)
      at Module._compile (internal/modules/cjs/loader.js:1075:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
      at Module.load (internal/modules/cjs/loader.js:940:32)
      at Function.Module._load (internal/modules/cjs/loader.js:781:14)
      at Module.require (internal/modules/cjs/loader.js:964:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at /Users/ryusi/home/oss/github/fav/test/fav-test.console-reporter/node_modules/yargs/lib/command.js:241:49



